### ISSUE TITLE
Guardar las revisiones de los extintores de Grupo Continental

### ISSUE THREAD

**Issue by georgyserea** [manuelcalerosolis/Gestool#10]
Necesitan guardar las fechas de las pruebas hidráulicas, fecha de próxima revisión, hacer búsquedas de extintores por el numero de placa, y poder hacer consultas del historial de cada cliente que, los extintores tiene y las fechas de la primera y ultima fecha de revisión

**Comment by watchoficina** [comment]
Hay que sentarse con ellos a verlo
