### ISSUE TITLE
Comprobar el calculo de stock de los artículos, le esta sumando albaranes que ya están facturados

### ISSUE THREAD

**Issue by georgyserea** [manuelcalerosolis/Gestool#22]
Baterías Huelva

**Comment by georgyserea** [comment]
ejemplo el articulo 533088, tiene albaranes que se han pasado a facturas, por el método de agrupar albaranes en facturas. Sospecho que no tienen bien el lógico de facturas.

**Comment by watchoficina** [comment]
no entran los albaranes sin facturar, ni los de proveedor, ni los de clientes.
